{% set name = "bionc" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ipuch/bioNC/archive/{{ version }}.tar.gz
  sha256: 84f657cd5a0fe21dfc016b0aa902151d41fc5fffa08140efad5dbaeab48bff56

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - scipy
    - numpy
    - packaging
    - casadi
    - ezc3d
    - plotly
    - bioviz
    - pyomeca
    - dill

test:
  imports:
    - bionc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Ipuch/bioNC
  summary: Natural Coordinates with python for biomechanics
  description: |
    This repository contains the source code for the bioNC library, a python package for biomechanics and natural coordinates formalism. Inverse and Forward approach are implemented.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/Ipuch/bioNC

extra:
  recipe-maintainers:
    - ipuch
