{% set name = "bionc" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Ipuch/bioNC/archive/{{ version }}.tar.gz
  sha256: da59bb6710822ba650e5b64431f008a51b7ae2c871ebe87db044ba0201c9319b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - scipy
    - numpy
    - packaging
    - casadi
    - ezc3d
    - plotly

test:
  imports:
    - bionc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/Ipuch/bioNC
  summary: Natural Coordinates with python for biomechanics
  description: |
    This repository contains the source code for the bioNC library, a python package for biomechanics and natural coordinates formalism. Inverse and Forward approach are implemented.
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/Ipuch/bioNC

extra:
  recipe-maintainers:
    - ipuch
